version: '3.1'

networks:
  web:
    ipam:
      config:
        - subnet: 172.20.10.0/29

services:
  server:
    build: .
    ports:
      - "8090:8080"
    depends_on:
      - postgres
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres:5432/ecommerce
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=postgres
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
      - SPRING_JPA_SHOW_SQL=true
    restart: always
    networks:
      web:
        ipv4_address: 172.20.10.3
  postgres:
    image: postgres:latest
    restart: always
    ports:
        - "5433:5432"
    volumes:
        - ./postgres:/var/lib/postgresql
    environment:
        - POSTGRES_USER=postgres
        - POSTGRES_DB=ecommerce
        - POSTGRES_PASSWORD=postgres
    networks:
        web:
          ipv4_address: 172.20.10.4

 